/* Generated by wayland-scanner 1.23.1 */

#ifndef WINFUSION_BUFFER_V1_CLIENT_PROTOCOL_H
#define WINFUSION_BUFFER_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_winfusion_buffer_v1 The winfusion_buffer_v1 protocol
 * zero-copy AHardwareBuffer buffers for WinFusion
 *
 * @section page_desc_winfusion_buffer_v1 Description
 *
 * WinFusion private protocol for compositor-allocated AHardwareBuffers.
 *
 * The compositor allocates the AHardwareBuffer, sends its handle through the
 * socket supplied by the client, and imports the same buffer as an EGLImage.
 * The client imports the received dma-buf into Vulkan, so both sides use the
 * same gralloc allocation without loading Android private libraries in the
 * client process.
 *
 * This is the Android equivalent of zwp_linux_dmabuf_v1: it exists because
 * Android EGL does not expose EGL_EXT_image_dma_buf_import.
 *
 * @section page_ifaces_winfusion_buffer_v1 Interfaces
 * - @subpage page_iface_zwp_winfusion_buffer_v1 - create zero-copy AHardwareBuffer wl_buffers
 * @section page_copyright_winfusion_buffer_v1 Copyright
 * <pre>
 *
 * Copyright © 2026 WinFusion
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 * </pre>
 */
struct wl_buffer;
struct zwp_winfusion_buffer_v1;

#ifndef ZWP_WINFUSION_BUFFER_V1_INTERFACE
#define ZWP_WINFUSION_BUFFER_V1_INTERFACE
/**
 * @page page_iface_zwp_winfusion_buffer_v1 zwp_winfusion_buffer_v1
 * @section page_iface_zwp_winfusion_buffer_v1_desc Description
 *
 * This global provides a way to create wl_buffer objects backed by
 * AHardwareBuffers allocated by the compositor and shared through a socket.
 * @section page_iface_zwp_winfusion_buffer_v1_api API
 * See @ref iface_zwp_winfusion_buffer_v1.
 */
/**
 * @defgroup iface_zwp_winfusion_buffer_v1 The zwp_winfusion_buffer_v1 interface
 *
 * This global provides a way to create wl_buffer objects backed by
 * AHardwareBuffers allocated by the compositor and shared through a socket.
 */
extern const struct wl_interface zwp_winfusion_buffer_v1_interface;
#endif

#define ZWP_WINFUSION_BUFFER_V1_CREATE_BUFFER 0


/**
 * @ingroup iface_zwp_winfusion_buffer_v1
 */
#define ZWP_WINFUSION_BUFFER_V1_CREATE_BUFFER_SINCE_VERSION 1

/** @ingroup iface_zwp_winfusion_buffer_v1 */
static inline void
zwp_winfusion_buffer_v1_set_user_data(struct zwp_winfusion_buffer_v1 *zwp_winfusion_buffer_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) zwp_winfusion_buffer_v1, user_data);
}

/** @ingroup iface_zwp_winfusion_buffer_v1 */
static inline void *
zwp_winfusion_buffer_v1_get_user_data(struct zwp_winfusion_buffer_v1 *zwp_winfusion_buffer_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) zwp_winfusion_buffer_v1);
}

static inline uint32_t
zwp_winfusion_buffer_v1_get_version(struct zwp_winfusion_buffer_v1 *zwp_winfusion_buffer_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) zwp_winfusion_buffer_v1);
}

/** @ingroup iface_zwp_winfusion_buffer_v1 */
static inline void
zwp_winfusion_buffer_v1_destroy(struct zwp_winfusion_buffer_v1 *zwp_winfusion_buffer_v1)
{
	wl_proxy_destroy((struct wl_proxy *) zwp_winfusion_buffer_v1);
}

/**
 * @ingroup iface_zwp_winfusion_buffer_v1
 *
 * Creates a wl_buffer backed by an AHardwareBuffer.
 *
 * The compositor allocates an AHardwareBuffer compatible with the
 * requested geometry and format, then writes a small layout header and
 * the serialized AHardwareBuffer handle to socket_fd. The client imports
 * the first dma-buf fd from that handle into Vulkan.
 *
 * The format argument is the DRM fourcc of the buffer contents as read
 * by the compositor.
 */
static inline struct wl_buffer *
zwp_winfusion_buffer_v1_create_buffer(struct zwp_winfusion_buffer_v1 *zwp_winfusion_buffer_v1, int32_t width, int32_t height, uint32_t format, int32_t socket_fd)
{
	struct wl_proxy *id;

	id = wl_proxy_marshal_flags((struct wl_proxy *) zwp_winfusion_buffer_v1,
			 ZWP_WINFUSION_BUFFER_V1_CREATE_BUFFER, &wl_buffer_interface, wl_proxy_get_version((struct wl_proxy *) zwp_winfusion_buffer_v1), 0, NULL, width, height, format, socket_fd);

	return (struct wl_buffer *) id;
}

#ifdef  __cplusplus
}
#endif

#endif
